name: Hadolint

on:
  workflow_call:
    inputs:
      runner:
        description: "Runner label or hosted runner name."
        type: string
        required: false
        default: ubuntu-latest
      dockerfile-path:
        description: "Path to the Dockerfile to lint."
        type: string
        default: "Dockerfile"

permissions:
  contents: read

jobs:
  hadolint:
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ inputs.dockerfile-path }}
